<a href="https://colab.research.google.com/github/RepoRecipee/IIIT-PROJECTS-AND-LABS/blob/main/MY%20FIRST%20ASSIGNMENT(Linear__Algebra).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Utilize the NumPy library for Linear Algebra operations and employ Matplotlib for plotting purposes.

In [7]:
import numpy as np
import matplotlib.pyplot as plt


finding the transpose of a nested list using NumPy method.,

In [8]:
a=[[13,10,23],[27,1,17]]
b=np.transpose(a)
print('a\n',a)
print('b\n',b)

a
 [[13, 10, 23], [27, 1, 17]]
b
 [[13 27]
 [10  1]
 [23 17]]


In [4]:
!pip install numpy


If Matrix is a Numpy array

In [11]:
matrix=np.array([[7,8,9,10],[1,2,9,5]])
transpose_matrix=matrix.T
print("original matrix")
print(matrix)
print("\ntranspose Matrix:")
print(transpose_matrix)

original matrix
[[ 7  8  9 10]
 [ 1  2  9  5]]

transpose Matrix:
[[ 7  1]
 [ 8  2]
 [ 9  9]
 [10  5]]


Transpose of Multidimensional Array

In [12]:
array = np.array([[[1, 2, 3],
                   [4, 5, 6]],

                  [[7, 8, 9],
                   [10, 11, 12]]])
print("Original Array:")
print(array)
transposed_array = np.transpose(array, axes=(1, 0, 2))
print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Transposed Array:
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


The dot method of NumPy performs dot-matrix product for 1D

In [13]:
a=9
b=4
result=np.dot(a,b)
print(result)

36


The dot method of NumPy performs on High Dimensional **arrays**

In [14]:
a=np.array([1,2,3])
b=np.array([6,9,3])
result=np.dot(a,b)
print("the dot of high dimensional arrays")
print(result)

the dot of high dimensional arrays
33


The dot method of NumPy performs on **2D **

In [16]:
a=np.array([[[1,2,3],[4,8,5],[6,0,1]]])
b=np.array([[[5,6,7],[9,6,8],[1,3,2]]])
result=np.dot(a,b)
print(result)

[[[[ 26  27  29]]

  [[ 97  87 102]]

  [[ 31  39  44]]]]


The np.matmul() function in NumPy is used for matrix multiplication. It computes the matrix product of two arrays, resulting in a new array.

In [17]:
result=np.matmul(a,b)
print(result)

[[[ 26  27  29]
  [ 97  87 102]
  [ 31  39  44]]]


# **Numpy Arrays**

A NumPy array is a Numpy object upon which the dot method can be performed as below

In [18]:
one=np.array(a)
two=np.array(b)
result=one.dot(two)
print(result)

[[[[ 26  27  29]]

  [[ 97  87 102]]

  [[ 31  39  44]]]]


## multi_dot method

Performing Dot product with 2 or more Matrices


In [94]:
# matrices with random integers: entries ranging from -7 to 7
a=np.random.randint(-7,7,(200,7))
b=np.random.randint(-7,7,(7,10))
c=np.random.randint(-7,7,(10,87))
d=np.random.randint(-7,7,(87,9))
# multiple matrix multiplication
result=np.linalg.multi_dot([a,b,c,d])



In [95]:
%%time
 z = np.linalg.multi_dot([a,b,c,d])
 print(z, '\n')

[[ -8279 -32146  13995 ...   1711   2095  47329]
 [ -6061  13593 -22247 ...  17876  16053 -19157]
 [ -7191  13843   3933 ... -13720 -14915 -18699]
 ...
 [-36094  25459   9022 ... -21355 -16876  -8302]
 [ 15701 -40705  17323 ...  -8833 -12258  12535]
 [  2443  24485  -6928 ... -18985 -17833 -21571]] 

CPU times: user 2.1 ms, sys: 0 ns, total: 2.1 ms
Wall time: 2.1 ms


In [29]:
%%time
result=a.dot(b).dot(c).dot(d)
print(result)

[[-39373 -20144 -30273 ... -18168  13626  17994]
 [ 10764  16443   6067 ...  29317 -34035  24315]
 [ -2188   -455 -26111 ... -25460  15720 -15300]
 ...
 [-21270 -12366  21099 ...  10414  -3855  14657]
 [ -5047    361  10211 ...   5869   -788  22000]
 [ 27316  23516 -12805 ...   9842 -17355  23631]]
CPU times: user 2.08 ms, sys: 0 ns, total: 2.08 ms
Wall time: 2.08 ms


Comparing the CPU time consumed by np.linalg.multi_dot() versus successive dot methods (a.dot(b).dot(c)) for arriving at the same solution can provide insights into their efficiency.

**Inner** **Product**

The inner product, also known as the dot product in the context of vectors, is a fundamental operation in linear algebra

In [32]:
a=np.array([1,9,0])
b=np.array([7,9,4])
result=np.inner(a,b)
print("inner product")
print(result)

inner product
88


In [33]:
result2=np.dot(a,b)
print(result2)

88


#same result for both inner and dot product

**Outer** **product**

In NumPy, you can compute the outer product of two vectors using the np.outer() function.

In [34]:
a=np.array([1,3,2])
b=np.array([9,8,5])
result=np.outer(a,b)
print(result)

[[ 9  8  5]
 [27 24 15]
 [18 16 10]]


@ operator is used for matrix multiplication

In [35]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
result_matrix = matrix_a @ matrix_b

print("Matrix multiplication using @ operator:")
print(result_matrix)

Matrix multiplication using @ operator:
[[19 22]
 [43 50]]


In [36]:
print(result_matrix.shape)

(2, 2)


**Matrix Determinant**

In [40]:
a=np.random.randint(7,18,[4,4])
result=np.linalg.det(a)
print(result)

455.9999999999998


**INVERSE**

In [41]:
print("before inverse")
print(a)
print("after inverse")
result2=np.linalg.inv(a)
print(result2)

before inverse
[[16 11 12 16]
 [12 12  9  9]
 [ 9  7 14 11]
 [14  9  9 15]]
after inverse
[[ 1.55921053 -0.30921053 -0.35526316 -1.21710526]
 [-1.02631579  0.35964912  0.15789474  0.76315789]
 [ 0.32236842 -0.07236842  0.06578947 -0.34868421]
 [-1.03289474  0.11622807  0.19736842  0.95394737]]


**Matrix Power**

np.linalg.matrix_power() function. This function computes the power of a given square matrix, either a positive, zero, or negative integer power.

In [51]:
a=np.random.randint(1,17,[4,4])
a_2=np.linalg.matrix_power(a,2)
a_6=np.linalg.matrix_power(a,6)
print('matrix to power 2\n',a_2)
print(  )
print('matrix to power 6\n',a_6)

matrix to power 2
 [[221 444 350 405]
 [199 427 305 375]
 [139 343 298 296]
 [224 518 369 515]]

matrix to power 6
 [[376132060 840822337 633831700 774292775]
 [346827987 775267118 584373025 713949560]
 [282118182 630721424 475499901 580759183]
 [434900847 972170044 732665482 895404447]]


In [49]:
a_inv_1=np.linalg.matrix_power(a,1)
print(a_inv_1)

[[15 12  9 14]
 [ 8  7  3 11]
 [ 3 10 14 16]
 [ 5  3 12 10]]


Eigenvalues and **Eigenvectors**

In NumPy, you can compute the eigenvalues and eigenvectors of a square matrix using the np.linalg.eig() function.

In [56]:
a = np.arange(4).reshape(2,2)
print(a)

[[0 1]
 [2 3]]


In [62]:
eig_val, eig_vec = np.linalg.eig(a)
print('Eigenvalues are:\n', eig_val)
print('Eigenvectors are:\n', eig_vec)

Eigenvalues are:
 [-0.56155281  3.56155281]
Eigenvectors are:
 [[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


Eigen values can be known by using np.linalg.eigvals()


In [74]:
a=np.arange(16).reshape(4,4)
print(a)
eig_val=np.linalg.eigvals(a)
print("eigen values\n")
print(eig_val)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
eigen values

[ 3.24642492e+01 -2.46424920e+00  1.64176007e-15 -1.10576860e-16]


**Traces of a Matrix**

Trace is the sum of all elements present in diagonal

In [76]:
a = np.eye(3)
print(a)
b=np.trace(a)
print("trace of matrix\n",b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
trace of matrix
 3.0


**Matrix Norm**

**computing different norms using the np.linalg.norm() function.**

In [78]:
a=np.arange(16).reshape(4,4)
b=np.linalg.norm(a)
print("NORM OF MATRIX")
print(b)

NORM OF MATRIX
35.21363372331802


**System of Equations**

np.linalg.solve is a function in NumPy used to solve a system of linear equations.

In [88]:






# Define a new coefficient matrix with adjusted values
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])  # Adjusted the last element from 9 to 10

# Dependent variable vector
b = np.array([1, 2, 3])

# Solve the system
result = np.linalg.solve(a, b)

print("Coefficient Matrix (a):")
print(a)

print("\nDependent Variable vector (b):")
print(b)

print("\nSolution:")
print(result)


Coefficient Matrix (a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

Dependent Variable vector (b):
[1 2 3]

Solution:
[-0.33333333  0.66666667 -0.        ]


checking for correctness


In [92]:
z=a.dot(result)
print(z)

[1. 2. 3.]
